dockerhub:
  "mozilla/stub_attribution":
    triggers:
      dev:
        tag: /^latest$/
        jobs:
          - path: /job/pipelines/job/stub_attribution
            tagParam: 'stubAttributionTag'
      stage:
        tag: /^v\d/
        jobs:
          - path: /job/pipelines/job/stub_attribution
            tagParam: 'stubAttributionTag'
